name: Android APK Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FLUTTER_VERSION: 3.16.5
  JAVA_VERSION: '17'
  GRADLE_VERSION: '8.2'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - name: Install dependencies
        run: |
          flutter pub get
          flutter pub run flutter_launcher_icons
      
      - name: Create local.properties
        run: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      
      - name: Grant execute permission for gradlew
        run: |
          cd android
          chmod +x gradlew
      
      - name: Build APK
        run: |
          flutter build apk --release
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/apk/release/app-release.apk
