name: Android APK Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FLUTTER_VERSION: 3.16.5

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - name: Create android directory structure
        run: |
          mkdir -p android/app/src/main/kotlin/com/alka/oiltracker
          mkdir -p android/app/src/main/res/drawable
          mkdir -p android/app/src/main/res/values
          mkdir -p android/gradle/wrapper
      
      - name: Download Gradle Wrapper
        run: |
          cd android
          wget -O gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/master/gradle/wrapper/gradle-wrapper.jar
          wget -O gradlew https://raw.githubusercontent.com/gradle/gradle/master/gradlew
          chmod +x gradlew
          cd ..
      
      - name: Install dependencies
        run: |
          flutter pub get
          flutter pub run flutter_launcher_icons
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease
          cd ..
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
